export const achievementsData = [
  {
    id: 1,
    title: "Cara Buat Server Proxmox-mu Anti Down",
    src: "/achieve/01.png",
    alt: "gambar 1",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-12",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Juni 2025",
    description:
      "Panduan lengkap untuk membuat server Proxmox lebih stabil dan anti down.",
    category: "sertifikat",
    level: "Advanced",
    link: "https://example.com/certificate/1",
    tags: ["Server", "Networking", "Proxmox"],
  },
  {
    id: 2,
    title: "Mengoptimalkan Kinerja Docker Container",
    src: "/achieve/01.png",
    alt: "gambar 2",
    width: 150,
    height: 75,
    className: "object-cover rounded-md rotate-12",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Mei 2025",
    description:
      "Tips dan trik meningkatkan performa container Docker di server produksi.",
    category: "badge",
    level: "Intermediate",
    link: "https://example.com/badge/2",
    tags: ["DevOps", "Docker"],
  },
  {
    id: 3,
    title: "Membuat Dashboard Monitoring Realtime",
    src: "/achieve/01.png",
    alt: "gambar 3",
    width: 150,
    height: 75,
    className: "object-cover rounded-md",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "April 2025",
    description:
      "Membuat dashboard realtime untuk memonitor server, database, dan IoT devices.",
    category: "sertifikat",
    level: "Advanced",
    link: "https://example.com/certificate/3",
    tags: ["Monitoring", "Dashboard", "IoT"],
  },
  {
    id: 4,
    title: "Implementasi Security Best Practices",
    src: "/achieve/01.png",
    alt: "gambar 4",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-6",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Maret 2025",
    description:
      "Mengamankan server dan aplikasi dengan standar keamanan terbaik.",
    category: "badge",
    level: "Advanced",
    link: "https://example.com/badge/4",
    tags: ["Security", "Best Practices"],
  },
  {
    id: 5,
    title: "Implementasi Security Best Practices",
    src: "/achieve/01.png",
    alt: "gambar 4",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-6",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Maret 2025",
    description:
      "Mengamankan server dan aplikasi dengan standar keamanan terbaik.",
    category: "badge",
    level: "Advanced",
    link: "https://example.com/badge/4",
    tags: ["Security", "Best Practices"],
  },
  {
    id: 6,
    title: "Implementasi Security Best Practices",
    src: "/achieve/01.png",
    alt: "gambar 4",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-6",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Maret 2025",
    description:
      "Mengamankan server dan aplikasi dengan standar keamanan terbaik.",
    category: "badge",
    level: "Advanced",
    link: "https://example.com/badge/4",
    tags: ["Security", "Best Practices"],
  },
  {
    id: 7,
    title: "Implementasi Security Best Practices",
    src: "/achieve/01.png",
    alt: "gambar 4",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-6",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Maret 2025",
    description:
      "Mengamankan server dan aplikasi dengan standar keamanan terbaik.",
    category: "badge",
    level: "Advanced",
    link: "https://example.com/badge/4",
    tags: ["Security", "Best Practices"],
  },
  {
    id: 8,
    title: "Implementasi Security Best Practices",
    src: "/achieve/01.png",
    alt: "gambar 4",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-6",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Maret 2025",
    description:
      "Mengamankan server dan aplikasi dengan standar keamanan terbaik.",
    category: "badge",
    level: "Advanced",
    link: "https://example.com/badge/4",
    tags: ["Security", "Best Practices"],
  },
  {
    id: 9,
    title: "Implementasi Security Best Practices",
    src: "/achieve/01.png",
    alt: "gambar 4",
    width: 150,
    height: 75,
    className: "object-cover rounded-md -rotate-6",
    issuer: "ID Networkers",
    label: "issued on",
    issueDate: "Maret 2025",
    description:
      "Mengamankan server dan aplikasi dengan standar keamanan terbaik.",
    category: "badge",
    level: "Advanced",
    link: "https://example.com/badge/4",
    tags: ["Security", "Best Practices"],
  },
];
