export const experienceData = [
  {
    id: 1,
    companyLogo: "/logo/flashcom.png",
    title: "Backend Golang Developer",
    company: "Pt. Affan Technology Indonesia (Parto.id)",
    location: "Jambi, Indonesia",
    period: "Jul 2025 – Sep 2025",
    duration: "2 Months",
    type: "Internship",
    mode: "Onsite",
    responsibilities: [
      "Developed and maintained backend services using Golang for Parto.id's internal attendance application.",
      "Implemented efficient data handling and secure API integrations to support daily attendance workflows.",
      "Collaborated with frontend and product teams to ensure smooth functionality and seamless user experience.",
    ],
  },
  {
    id: 2,
    companyLogo: "/logo/flashcom.png",
    title: "Frontend React Developer",
    company: "PT. Contoh Perusahaan",
    location: "Jakarta, Indonesia",
    period: "Jan 2025 – Mar 2025",
    duration: "3 Months",
    type: "Internship",
    mode: "Remote",
    responsibilities: [
      "Built reusable React components and integrated with backend APIs.",
      "Worked on responsive UI and performance optimization.",
    ],
  },
  {
    id: 3,
    companyLogo: "/logo/flashcom.png",
    title: "UI/UX Designer",
    company: "PT. Kreatif Digital",
    location: "Bandung, Indonesia",
    period: "Apr 2025 – Jun 2025",
    duration: "3 Months",
    type: "Freelance",
    mode: "Remote",
    responsibilities: [
      "Designed interactive UI mockups and prototypes using Figma.",
      "Collaborated with frontend developers to implement responsive designs.",
    ],
  },
  {
    id: 4,
    companyLogo: "/logo/flashcom.png",
    title: "Data Analyst Intern",
    company: "PT. Data Insight",
    location: "Surabaya, Indonesia",
    period: "Feb 2025 – May 2025",
    duration: "4 Months",
    type: "Internship",
    mode: "Onsite",
    responsibilities: [
      "Analyzed datasets to extract actionable insights for business decisions.",
      "Prepared reports and dashboards using Power BI and Excel.",
    ],
  },
  {
    id: 5,
    companyLogo: "/logo/flashcom.png",
    title: "Machine Learning Researcher",
    company: "Institut Teknologi AI",
    location: "Yogyakarta, Indonesia",
    period: "Mar 2025 – Jul 2025",
    duration: "5 Months",
    type: "Research",
    mode: "Onsite",
    responsibilities: [
      "Developed machine learning models for image classification tasks.",
      "Collaborated with team members to write research papers and present findings.",
    ],
  },
];
